platform :ios, '7.0'
target 'OptionalHome' do

pod 'AFNetworking', '~> 3.1.0'
pod 'SDWebImage', '~> 3.8.1'
pod 'MBProgressHUD', '~> 1.0.0'
pod "WeiboSDK", :git => "https://github.com/sinaweibosdk/weibo_ios_sdk.git" 
pod 'MJExtension', '~> 3.0.13'
pod 'BaiduMapKit'
pod 'MJRefresh', '~> 3.1.12'

end
